[package]
name              = "xtask"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow  = "1.0"
clap    = { version = "4.5", features = ["derive"] }
cmd_lib = "2.0"
walkdir = "2.5"
sha2    = "0.10"
