[package]
name              = "kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name  = "kernel"
test  = false
bench = false

[dependencies]
sbi-rt.workspace = true
riscv            = "0.16"
