[alias]
run-core   = "run -r --bin xtask -- run"   # --release
build-core = "run -r --bin xtask -- build" # --release

clippy-core  = "clippy --package core --target riscv64gc-unknown-none-elf"
clippy-xtask = "clippy --package xtask"
